# Generated by Django 6.1.1 on 2026-09-18 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_fooddonation_image'),
        ('requests_app', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='donation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donations.fooddonation'),
        ),
    ]
