# Generated by Django 6.1.1 on 2026-09-13 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('cooked', 'Cooked Food'), ('raw', 'Raw Food'), ('bakery', 'Bakery'), ('packaged', 'Packaged Food'), ('other', 'Other')], max_length=20)),
                ('quantity', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('preparation_time', models.DateTimeField(blank=True, null=True)),
                ('expiry_time', models.DateTimeField()),
                ('pickup_location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('requested', 'Requested'), ('accepted', 'Accepted'), ('collected', 'Collected'), ('completed', 'Completed')], default='posted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
